### ISSUE TITLE
fails to run on openshift

### ISSUE THREAD

**Issue by syamgk** [mohammedzee1000/postgres#2]
log from openshift:
mkdir: cannot create directory ‘/var/lib/pgsql’: Permission denied

I suspect the commands running inside the docker-entrypoint.sh
chmod, chown, gosu are the blocking factors.

**Comment by mohammedzee1000** [comment]
@syamgk Once verification is complete, please send a PR so that the r.c.o containers can also be updated. Note the containers will be life cycled there so it will be good idea to get it on the container pipeline.
